src/Entity/Hiking.php
<?php

namespace App\Entity;

use App\Repository\HikingRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=HikingRepository::class)
 */
class Hiking
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="time")
     */
    private $duration;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $distance;

    /**
     * @ORM\Column(type="integer")
     */
    private $elevation_gain;

    /**
     * @ORM\Column(type="integer")
     */
    private $highest_point;

    /**
     * @ORM\Column(type="integer")
     */
    private $lowest_point;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $return_start_point;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $region;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $municipality;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $picture;

    /**
     * @ORM\Column(type="datetime_immutable", nullable=true)
     */
    private $modified_at;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $created_at;

    /**
     * @ORM\ManyToOne(targetEntity=HikingDifficulty::class, inversedBy="hikings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $difficulty;

    /**
     * @ORM\ManyToOne(targetEntity=HikingType::class, inversedBy="hikings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $type;

    /**
     * @ORM\OneToMany(targetEntity=WayPoint::class, mappedBy="hiking", orphanRemoval=true)
     */
    private $wayPoints;

    public function __construct()
    {
        $this->wayPoints = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDuration(): ?\DateTimeInterface
    {
        return $this->duration;
    }

    public function setDuration(\DateTimeInterface $duration): self
    {
        $this->duration = $duration;

        return $this;
    }

    public function getDistance(): ?string
    {
        return $this->distance;
    }

    public function setDistance(string $distance): self
    {
        $this->distance = $distance;

        return $this;
    }

    public function getElevationGain(): ?int
    {
        return $this->elevation_gain;
    }

    public function setElevationGain(int $elevation_gain): self
    {
        $this->elevation_gain = $elevation_gain;

        return $this;
    }

    public function getHighestPoint(): ?int
    {
        return $this->highest_point;
    }

    public function setHighestPoint(int $highest_point): self
    {
        $this->highest_point = $highest_point;

        return $this;
    }

    public function getLowestPoint(): ?int
    {
        return $this->lowest_point;
    }

    public function setLowestPoint(int $lowest_point): self
    {
        $this->lowest_point = $lowest_point;

        return $this;
    }

    public function getReturnStartPoint(): ?bool
    {
        return $this->return_start_point;
    }

    public function setReturnStartPoint(?bool $return_start_point): self
    {
        $this->return_start_point = $return_start_point;

        return $this;
    }

    public function getRegion(): ?string
    {
        return $this->region;
    }

    public function setRegion(string $region): self
    {
        $this->region = $region;

        return $this;
    }

    public function getMunicipality(): ?string
    {
        return $this->municipality;
    }

    public function setMunicipality(string $municipality): self
    {
        $this->municipality = $municipality;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getModifiedAt(): ?\DateTimeImmutable
    {
        return $this->modified_at;
    }

    public function setModifiedAt(?\DateTimeImmutable $modified_at): self
    {
        $this->modified_at = $modified_at;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getDifficulty(): ?HikingDifficulty
    {
        return $this->difficulty;
    }

    public function setDifficulty(?HikingDifficulty $difficulty): self
    {
        $this->difficulty = $difficulty;

        return $this;
    }

    public function getType(): ?HikingType
    {
        return $this->type;
    }

    public function setType(?HikingType $type): self
    {
        $this->type = $type;

        return $this;
    }

    /**
     * @return Collection|WayPoint[]
     */
    public function getWayPoints(): Collection
    {
        return $this->wayPoints;
    }

    public function addWayPoint(WayPoint $wayPoint): self
    {
        if (!$this->wayPoints->contains($wayPoint)) {
            $this->wayPoints[] = $wayPoint;
            $wayPoint->setHiking($this);
        }

        return $this;
    }

    public function removeWayPoint(WayPoint $wayPoint): self
    {
        if ($this->wayPoints->removeElement($wayPoint)) {
            // set the owning side to null (unless already changed)
            if ($wayPoint->getHiking() === $this) {
                $wayPoint->setHiking(null);
            }
        }

        return $this;
    }

}

src/Controller/HikingController.php
<?php

namespace App\Controller;

use App\Entity\Hiking;
use App\Entity\HikingType as HikingTypes;
use App\Entity\HikingDifficulty;
use App\Entity\WayPoint;

use App\Repository\HikingRepository;
use App\Repository\WayPointRepository;

use App\Form\HikingType;
use App\Form\SearchType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\RangeType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;

use phpGPX\Models\GpxFile;
use phpGPX\Models\Point;
use phpGPX\Models\Segment;
use phpGPX\Models\Track;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Knp\Component\Pager\PaginatorInterface;

/**
 * @Route("/hiking", name="hiking.")
 */
class HikingController extends AbstractController
{
    public function __construct()
    {
        
    }
    
    /**
     * @Route("/", name="index", methods={"GET"})
     */
    public function index(HikingRepository $hikingRepository, PaginatorInterface $paginator, Request $request): Response
    {
        $data    = $hikingRepository->findBy([],['created_at' => 'desc']);
        $hikings = $paginator->paginate($data, $request->query->getInt('page', 1), 5);

        return $this->render('hiking/index.html.twig', [
            'hikings'       => $hikings,
        ]);
    }

    public function search(): Response
    {
        $form = $this->createFormBuilder(null)
            ->setAction($this->generateUrl('hiking.handleSearch'))
            ->add('search', TextType::class,[
                'required' => false,
            ])
            ->add('difficulty_min', HiddenType::class,[
                'required' => false,
            ])
            ->add('difficulty_max', HiddenType::class,[
                'required' => false,
            ])
            ->add('duration_min', HiddenType::class,[
                'required' => false,
            ])
            ->add('duration_max', HiddenType::class,[
                'required' => false,
            ])
            ->add('type', EntityType::class,[
                'class' => HikingTypes::class,
                'label' => 'Type',
                'placeholder' => 'Sélectionner une type',
                'mapped' => true,
                'required' => false,
            ])
            ->add('return_start_point', CheckboxType::class,[
                'required' => false
            ])
            ->add('submit', SubmitType::class)
            ->getForm();  

        return $this->render('hiking/search.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/handleSearch", name="handleSearch")
     */
    public function handleSearch(Request $request, HikingRepository $hikingRepository, PaginatorInterface $paginator)
    {
        $data    = $hikingRepository->findBySearch($request->request->get('form'));
        $hikings = $paginator->paginate($data, $request->query->getInt('page', 1), 5);

        return $this->render('hiking/index.html.twig', [
            'hikings' => $hikings,
        ]);
    }

    /**
     * @Route("/new", name="new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $hiking = new Hiking();
        $entityManager = $this->getDoctrine()->getManager();
        $form = $this->createForm(HikingType::class, $hiking);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $this->checkSetPicture($form['picture'], $hiking, $entityManager);
            $this->checkSetWayPoints($form->getExtraData()['wayPoints'], $hiking, $entityManager);
            $hiking->setCreatedAt(new \DateTimeImmutable());
            $entityManager->persist($hiking);
            $entityManager->flush();

            $request->attributes->set('id',$hiking->getId());
            $request->attributes->set('title',$hiking->getTitle());
            
            return $this->redirectToRoute('hiking.index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('hiking/new.html.twig', [
            'hiking' => $hiking,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}/show", name="show", methods={"GET"})
     */
    public function show(Hiking $hiking, WayPointRepository $wayPointRepository): Response
    {
        return $this->render('hiking/show.html.twig', [
            'hiking' => $hiking,
            'waypoints' => $wayPointRepository->findBy(['hiking' => $hiking->getId()])
        ]);
    }

    /**
     * @Route("/{id}/edit", name="edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Hiking $hiking, WayPointRepository $wayPointRepository): Response
    {
        $entityManager = $this->getDoctrine()->getManager();
        $form = $this->createForm(HikingType::class, $hiking);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $this->checkSetPicture($form['picture'], $hiking, $entityManager);
            if (isset($form->getExtraData()['wayPoints']))
                $this->checkSetWayPoints($form->getExtraData()['wayPoints'], $hiking, $entityManager);
            $hiking->setModifiedAt(new \DateTimeImmutable());
            $entityManager->flush();

            $request->attributes->set('id',$hiking->getId());
            $request->attributes->set('title',$hiking->getTitle());

            return $this->redirectToRoute('hiking.index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('hiking/edit.html.twig', [
            'hiking' => $hiking,
            'waypoints' => $wayPointRepository->findBy(['hiking' => $hiking->getId()]),
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}/delete", name="delete", methods={"POST"})
     */
    public function delete(Request $request, Hiking $hiking): Response
    {
        if ($this->isCsrfTokenValid('delete'.$hiking->getId(), $request->request->get('_token'))) {

            $request->attributes->set('id',$hiking->getId());
            $request->attributes->set('title',$hiking->getTitle());
            
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($hiking);
            $entityManager->flush();
        }

        return $this->redirectToRoute('hiking.index', [], Response::HTTP_SEE_OTHER);
    }

    /*
     * Gestion de l'upload d'image.
     */
    private function checkSetPicture($data, $hiking, $entityManager)
    {
        if ($data->getViewData() != null){
            $file = $data->getViewData();
            $filename = md5(uniqid()).'.'.$file->guessExtension();
            if ($file->move($this->getParameter('upload_path'),$filename)) {
                $hiking->setPicture($filename);
                return true;
            } else return false;
        } else true;
    }

    /*
     * Gestion des coordonnées GPS.
     */
    private function checkSetWayPoints($data, $hiking, $entityManager)
    {
        if (isset($data) && count($data) > 0 ) {
            if ($hiking->getId() != null) {
                $entities = $entityManager->getRepository(WayPoint::class)->findBy(['hiking'=>$hiking->getId()]);
                foreach ($entities as $entity) {$entityManager->remove($entity);}
            }
            foreach ($data as $key => $value) {
                $wayPoint = new wayPoint();
                $geo = explode(';',$value);
                $wayPoint->setHiking($hiking);
                $wayPoint->setStep($key+1);
                $wayPoint->setLongitude($geo[0]);
                $wayPoint->setLatitude($geo[1]);
                $entityManager->persist($wayPoint);        
            }
            return true;
        } else return false;
    }

    /**
     * @Route("/{id}/gpx", name="gpx", methods={"GET","POST"})
     */
    public function generateGpxFile($id)
    {
        $waypoints  = $this->getDoctrine()->getManager()->getRepository(WayPoint::class)->findBy(['hiking' => $id]);
        $hiking     = $this->getDoctrine()->getManager()->getRepository(Hiking::class)->find($id);
        $data       = [];

        foreach ($waypoints as $key => $val) {
            $data[] = [
                'longitude' => $val->getLongitude(),
                'latitude' => $val->getLatitude(),
                'step' => $val->getStep(),
            ];
        }

        $gpx_file    = new GpxFile();
        $track       = new Track();
        $track->name = $hiking->getTitle();
        $track->type = $hiking->getType();;
        $segment     = new Segment();

        foreach ($data as $data_point)
        {
            $point = new Point(Point::TRACKPOINT);
            $point->latitude = $data_point['latitude'];
            $point->longitude = $data_point['longitude'];
            $point->elevation = $data_point['step'];
            $segment->points[] = $point;
        }

        $track->segments[] = $segment;
        $track->recalculateStats();
        $gpx_file->tracks[] = $track;
        $gpx_file->save('CreatingFileFromScratchExample.gpx', \phpGPX\phpGPX::XML_FORMAT);
        $gpx_file->save('CreatingFileFromScratchExample.json', \phpGPX\phpGPX::JSON_FORMAT);

        header("Content-Type: application/gpx+xml");
        header("Content-Disposition: attachment; filename=cwtestrando-".$id.".gpx");
        echo $gpx_file->toXML()->saveXML();
        exit();
    }
}

templates/hiking/_delete_form.html.twig
<form method="post" action="{{ path('hiking.delete', {'id': hiking.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ hiking.id) }}">
    <button class="btn">Delete</button>
</form>

templates/hiking/_form.html.twig
{{ form_start(form) }}

    {{ form_widget(form) }}
    <div>
        <input id="geoInput" class="search" type="search" autocomplete="off">
        <button id="geoSubmit" type="button">Géographier</button>
    </div>
    <div id="geoContent"></div>
    <div id="geoValid">
        {% if waypoints is defined %}
        {% for point in waypoints %}
            <button type="button" class="valited" style="background-color: rgb(140, 217, 140);">
                Etape n°{{ point.step }}
                <small>{{ point.longitude }}, {{ point.latitude }}</small>
            </button>
        {% endfor %}
        {% endif %}
    </div>
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/hiking/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Hiking{% endblock %}

{% block body %}
    <h1>Edit Hiking</h1>

    {{ include('hiking/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('hiking.index') }}">back to list</a>

    {{ include('hiking/_delete_form.html.twig') }}
{% endblock %}

templates/hiking/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hiking index{% endblock %}

{% block body %}
    <h1>Hiking index</h1>
    
    <table class="table">
        <thead>
            <tr>
                <th>Title</th>
                <th>Distance</th>
                <th>Elevation_gain</th>
                <th>Region</th>
                <th>Municipality</th>
                <th>Picture</th>
                <th>Difficulty</th>
                <th>Type</th>
                <th>Created_at</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for hiking in hikings %}
            <tr>
                <td>{{ hiking.title }}</td>
                <td>{{ hiking.distance }}</td>
                <td>{{ hiking.elevationGain }}</td>
                <td>{{ hiking.region }}</td>
                <td>{{ hiking.municipality }}</td>
                <td><img width="170px" src="{% if hiking.picture is not null %}{{ asset('uploads/')~hiking.picture }}
                                            {% else %}{{ asset('assets/img/nopicture.png') }}{% endif %}">
                </td>
                <td>{{hiking.difficulty}}</td>
                <td>{{hiking.type}}</td>
                <td>{{ hiking.createdAt ? hiking.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('hiking.show', {'id': hiking.id}) }}">show</a>
                    <a href="{{ path('hiking.edit', {'id': hiking.id}) }}">edit</a>
                    <a href="{{ path('hiking.gpx', {'id': hiking.id}) }}">gpxFile</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="16">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {{ knp_pagination_render(hikings) }}

    <a href="{{ path('hiking.new') }}">Create new</a>
      
{% endblock %}


{% block javascript %}
<script>
  $( function() {
    let difficulties = ['facile', 'moyenne', 'difficile', 'très difficile'];
    $( "#slider-range-difficulty" ).slider({
        range: true,
        min: 1,
        max: 4,
        values: [ 1, 4 ],
        slide: function( event, ui ) {
            $( "#amount" ).val( "$" + ui.values[ 0 ] + " - $" + ui.values[ 1 ] );
            $('#form_difficulty_min').val(ui.values[0]);
            $('#form_difficulty_max').val(ui.values[1]);
            $('#difficulty-text').html('Difficulté de <b>'+difficulties[ui.values[0]-1]+'</b> à <b>'+difficulties[ui.values[1]-1]+'</b>');
        }
    });
    $( "#amount" ).val( "$" + $( "#slider-range-difficulty" ).slider( "values", 0 ) +
      " - $" + $( "#slider-range-difficulty" ).slider( "values", 1 ) );
    
    $( "#slider-range-duration" ).slider({
        range: true,
        min: 1,
        max: 24,
        values: [ 1, 24 ],
        slide: function( event, ui ) {
            $( "#amount" ).val( "$" + ui.values[ 0 ] + " - $" + ui.values[ 1 ] );
            $('#form_duration_min').val(ui.values[0]);
            $('#form_duration_max').val(ui.values[1]);
            $('#duration-text').html('Durée de <b>'+ui.values[0]+'h</b> à <b>'+ui.values[1]+'h</b>');
        }
    });
    $( "#amount" ).val( "$" + $( "#slider-range-duration" ).slider( "values", 0 ) +
      " - $" + $( "#slider-range-duration" ).slider( "values", 1 ) );
  } );
</script>
{% endblock %}

templates/hiking/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Hiking{% endblock %}

{% block body %}
    <h1>Create new Hiking</h1>

    {{ include('hiking/_form.html.twig') }}

    <a href="{{ path('hiking.index') }}">back to list</a>
{% endblock %}

templates/hiking/search.html.twig
{{ form_start(form) }}
    <div class="row">
        <div class="col">
            {{ form_row(form.search) }}
        </div>
        <div class="col">
            <span id="difficulty-text">Difficulté de <b>facile</b> à <b>très difficile</b></span>
            <div id="slider-range-difficulty"></div>
            {{ form_row(form.difficulty_min) }}
            {{ form_row(form.difficulty_max) }}
        </div>
        <div class="col">
            <span id="duration-text">Durée de <b>1h</b> à <b>24h</b></span>
            <div id="slider-range-duration"></div>
            {{ form_row(form.duration_min) }}
            {{ form_row(form.duration_max) }}
        </div>
        <div class="col">
            {{ form_row(form.type) }}
        </div>
        <div class="col">
            {{ form_row(form.return_start_point) }}
        </div>
         <div class="col">
            {{ form_row(form.submit) }}
        </div>
    </div>
{{ form_end(form) }}

templates/hiking/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hiking{% endblock %}

{% block body %}
    <h1>Hiking</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ hiking.id }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ hiking.email }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ hiking.title }}</td>
            </tr>
            <tr>
                <th>Duration</th>
                <td>{{ hiking.duration | date('H:i:s')}}</td>
            </tr>
            <tr>
                <th>Distance</th>
                <td>{{ hiking.distance }}</td>
            </tr>
            <tr>
                <th>Elevation_gain</th>
                <td>{{ hiking.elevationGain }}</td>
            </tr>
            <tr>
                <th>Highest_point</th>
                <td>{{ hiking.highestPoint }}</td>
            </tr>
            <tr>
                <th>Lowest_point</th>
                <td>{{ hiking.lowestPoint }}</td>
            </tr>
            <tr>
                <th>Return_start_point</th>
                <td>{{ hiking.returnStartPoint ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Region</th>
                <td>{{ hiking.region }}</td>
            </tr>
            <tr>
                <th>Municipality</th>
                <td>{{ hiking.municipality }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ hiking.description }}</td>
            </tr>
            <tr>
                <th>WayPoints</th>
                <td>
                {% for point in waypoints %}
                <tr>
                    <td>Etape n°{{ point.step }}</td>
                    <td>{{ point.longitude }}, {{ point.latitude }}</td>
                </tr>
                {% endfor %}
                </td>
            </tr>
            <tr>
                <th>Picture</th>
                <td>
                    <img width="170px" src="
                        {% if hiking.picture is not null %}
                            {{ asset('uploads/')~hiking.picture }}
                        {% else %}
                            {{ asset('assets/img/nopicture.png') }}
                        {% endif %}">
                </td>
            </tr>
            <tr>
                <th>Modified_at</th>
                <td>{{ hiking.modifiedAt ? hiking.modifiedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ hiking.createdAt ? hiking.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('hiking.index') }}">back to list</a>

    <a href="{{ path('hiking.edit', {'id': hiking.id}) }}">edit</a>

    {{ include('hiking/_delete_form.html.twig') }}
{% endblock %}

{% block javascript %}

{% endblock %}